### PR TITLE
Update CI.yml

### PR DESCRIPTION
**Pull request by MarkHarris21**

### CODE REVIEW

**Comment by effigies** [comment]
@Kyle-Mendes Cryptocurrency miner. Please cancel actions, report user and block.

**Comment by Kyle-Mendes** [comment]
Thank you for the heads up

**Comment by effigies** [comment]
FWIW looks like the close/reopen triggered more that haven't been cancelled.

**Comment by Kyle-Mendes** [comment]
Thanks! I thought I got them all. :)

**Pull request closed without merging**
